[theme]
primaryColor = "#60A54D"
backgroundColor = "#2c2c2c"
secondaryBackgroundColor = "#232323"
textColor = "#FFFFFF"
showWidgetBorder=true
borderColor = "#FFFFFF"
font = "'Cascadia Code':https://fonts.googleapis.com/css2?family=Cascadia+Code:ital,wght@0,200..700;1,200..700&display=swap"
